---
name: CI/CD

on:
  push:
    branches:
    - main
    - "dev-*"
  workflow_dispatch:

jobs:
  lint-code:
    name: Lint Code
    runs-on: ubuntu-22.04
    # environment: acc

    steps:
    - name: Download code
      uses: actions/checkout@v4

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Get and lint in MD files
      run: find . -name "*.md" -type f -exec markdownlint --config .markdownlint.json {} \;

    - name: Install proselint
      run: |
        sudo add-apt-repository universe
        sudo apt install python3-proselint

    - name: Get and lint written language in MD files
      run: find . -name "*.md" -type f -exec proselint {} \;

    - name: Publish MD file(s) into output
      id: publish
      run: find *.md -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'

    - name: Run Hadolint on Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    environment: acc
    needs: lint-code

    steps:
    - name: Build docker images
      run: docker build -t local < Dockerfile

  # deploy-to-prd:
  #   name: Deploy to Production
  #   runs-on: ubuntu-22.04
  #   environment: prd
  #   needs: lint-code!

  #   steps:
  #   - name: Download code
  #     uses: actions/checkout@v4

  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v3

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v3

  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v3
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}

  #   - name: Build and push
  #     uses: docker/build-push-action@v5
  #     with:
  #       push: true
  #       tags: davaba/terraform:latest

  # prd-test:
  #   name: Production Test
  #   runs-on: ubuntu-22.04
  #   environment: prd
  #   needs: lint-code!
