---
name: CI/CD

on:
  push:
    branches:
    - main
    - "dev-*"
  workflow_dispatch:

jobs:
  ci-lint-code:
    name: CI Lint Code
    runs-on: ubuntu-22.04
    environment: dev

    steps:
    - name: Download code
      uses: actions/checkout@v4

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Get and lint in MD files
      run: find . -name "*.md" -type f -exec markdownlint --config .markdownlint.json {} \;

    - name: Install proselint
      run: |
        sudo add-apt-repository universe
        sudo apt install python3-proselint

    - name: Get and lint written language in MD files
      run: find . -name "*.md" -type f -exec proselint {} \;

    - name: Publish MD file(s) into output
      id: publish
      run: find *.md -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'

    - name: Run Hadolint on Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile

  ci-build-and-test:
    name: CI Build and Test
    needs: ci-lint-code
    runs-on: ubuntu-22.04
    environment: acc

    steps:
    - name: Download code
      uses: actions/checkout@v4

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: local

    - name: Spawn container from local Docker image
      run: |
        docker run local:latest terraform --version
        docker run local:latest terragrunt --version

  cd-deploy-to-prd:
    name: CD Deploy to Production
    needs: ci-build-and-test
    runs-on: ubuntu-22.04
    environment: prd

    steps:
    - name: Download code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: davaba/terraform:latest

  prd-test:
    name: CD Production Test
    needs: cd-deploy-to-prd
    runs-on: ubuntu-22.04
    environment: prd

    steps:
    - name: Spawn container from public Docker image
      run: |
        docker run davaba/terraform:latest terraform --version
        docker run davaba/terraform:latest terragrunt --version
